sql.Query([[CREATE TABLE IF NOT EXISTS MurderSpecial ( 
    ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    MAP TEXT, 
    VIEWMODEL_GUN TEXT, 
    WORLDMODEL_GUN TEXT, 
    VIEWMODEL_KNIF TEXT, 
    WORLDMODEL_KNIF TEXT,
    USED INTEGER DEFAULT 1);
]])
sql.Query([[CREATE TABLE IF NOT EXISTS MurderSpecial_playermodel (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PLAYERMODEL TEXT,
    USED INTEGER DEFAULT 0,
    IDE INTEGER REFERENCES MurderSpecial(ID));
]])